services:
#  postgres:
#    image: postgres:17.0
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: jobsdb

  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - 15672:15672
      - 5672:5672